export const enum ERROR_TYPE{
    VALIDATION_ERROR='VALIDATION_ERROR',
    AUTHENTICATION_ERROR='AUTHENTICATION_ERROR',
    INTERNAL_SERVER_ERROR='INTERNAL_SERVER_ERROR',
    NO_DATA_FOUND = 'NO_DATA_FOUND'
}