version: '3'

services:
  clean-architecture:
    build: 
      context: ./dist/development
      dockerfile: DockerFile
    ports: 
      - "8080:80"
    volumes:
      - /usr/clean-architecture/node_modules
      - ./dist/development:/usr/clean-architecture/