export enum RESPONSE_STATUS {
    SUCCESS = "SUCCESS",
    FAIL    = "FAIL",
    ERROR   = "ERROR"
}

export enum ERROR_TO_STATUS{
    VALIDATION_ERROR=RESPONSE_STATUS.FAIL,
    AUTHENTICATION_ERROR=RESPONSE_STATUS.FAIL,
    INTERNAL_SERVER_ERROR=RESPONSE_STATUS.ERROR,
    NO_DATA_FOUND = RESPONSE_STATUS.ERROR
}