FROM node:10-alpine as builder
WORKDIR /usr/temp
COPY ./package*.json ./
RUN npm install
COPY . .
RUN npm run build:prod

FROM node:10-alpine
WORKDIR /usr/api
ENV NODE_ENV=production
EXPOSE 80
COPY --from=builder /usr/temp/dist/production .
RUN npm install --only=prod
CMD [ "npm","run", "start:prod" ]